[project]
name = "coremark-pe"

[target.coremark-pe]
type = "executable"
sources = ["src/**.c", "inc/**.h"]
include-directories = ["inc"]
compile-definitions = ["PERFORMANCE_RUN=1", "ITERATIONS=100000"]

cmake-before = """
add_link_options("/O2" "/DEBUG:FULL" "/LTCG" "/GL")
"""